services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/loopdin-api
    container_name: fastapi_backend
    command: uvicorn src.main.main:app --host 0.0.0.0 --port 9000
    environment:
      ENV: ${ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SES_SMTP_HOST: ${SES_SMTP_HOST}
      SES_SMTP_PORT: ${SES_SMTP_PORT}
      SES_SMTP_USERNAME: ${SES_SMTP_USERNAME}
      SES_SMTP_PASSWORD: ${SES_SMTP_PASSWORD}
      SES_FROM_EMAIL: ${SES_FROM_EMAIL}
    networks:
      - loopdin_net

  ui:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/loopdin-ui
    container_name: vite_frontend
    depends_on:
      - api
    networks:
      - loopdin_net
    # We'll run Nginx in this container as the frontend server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build:/usr/share/nginx/html:ro
    ports:
      - "80:80"

networks:
  loopdin_net:

volumes:
  postgres_data:
